# Sideloads Lucid Tabs into a Zen Browser profile.
# The Zen Mods "Import mods" button only installs mods published in the official
# theme store (it fetches by id and ignores every other field), so unpublished
# mods have to be installed by hand: copy the files into the profile, register
# the entry in zen-themes.json, and rebuild the compiled zen-themes.css that
# Zen actually injects at startup.
#
# Usage:  .\install.ps1 [-ProfilePath <full path to profile>] [-Uninstall]
# Run with Zen closed; changes take effect on next launch.

param(
    [string]$ProfilePath,
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"

$ModId = "52a805b5-2450-4f21-8664-d69bb96be507"
$RepoRoot = $PSScriptRoot
$theme = Get-Content (Join-Path $RepoRoot "theme.json") -Raw | ConvertFrom-Json

if (Get-Process zen -ErrorAction SilentlyContinue) {
    Write-Warning "Zen is running. Close it first: it only reads mods at startup, and may overwrite zen-themes.json while open."
    exit 1
}

# --- locate profile -----------------------------------------------------------
if (-not $ProfilePath) {
    $profilesDir = Join-Path $env:APPDATA "zen\Profiles"
    if (-not (Test-Path $profilesDir)) {
        Write-Error "Zen profiles directory not found at $profilesDir"
    }
    # Pick the profile used most recently (freshest prefs.js).
    $candidates = Get-ChildItem $profilesDir -Directory |
        Where-Object { Test-Path (Join-Path $_.FullName "prefs.js") } |
        Sort-Object { (Get-Item (Join-Path $_.FullName "prefs.js")).LastWriteTime } -Descending
    if (-not $candidates) {
        Write-Error "No Zen profile with a prefs.js found under $profilesDir"
    }
    $ProfilePath = $candidates[0].FullName
}
Write-Host "Profile: $ProfilePath"

$modsJsonPath = Join-Path $ProfilePath "zen-themes.json"
$modsRoot     = Join-Path $ProfilePath "chrome\zen-themes"
$compiledCss  = Join-Path $ProfilePath "chrome\zen-themes.css"
$modDir       = Join-Path $modsRoot $ModId

# --- update zen-themes.json ----------------------------------------------------
$mods = @{}
if (Test-Path $modsJsonPath) {
    $parsed = Get-Content $modsJsonPath -Raw | ConvertFrom-Json
    foreach ($p in $parsed.PSObject.Properties) { $mods[$p.Name] = $p.Value }
}

if ($Uninstall) {
    $mods.Remove($ModId) | Out-Null
    if (Test-Path $modDir) { Remove-Item $modDir -Recurse -Force }
} else {
    New-Item -ItemType Directory -Force $modDir | Out-Null
    foreach ($f in "chrome.css", "preferences.json", "readme.md") {
        Copy-Item (Join-Path $RepoRoot $f) (Join-Path $modDir $f) -Force
    }

    $rawBase = "https://raw.githubusercontent.com/Muowl/zen-lucid-tabs/main"
    $today = Get-Date -Format "yyyy-MM-dd"
    $mods[$ModId] = [ordered]@{
        id          = $ModId
        name        = $theme.name
        description = $theme.description
        homepage    = $theme.homepage
        style       = "$rawBase/chrome.css"
        readme      = "$rawBase/readme.md"
        preferences = "$rawBase/preferences.json"
        author      = $theme.author
        version     = $theme.version
        tags        = $theme.tags
        createdAt   = $today
        updatedAt   = $today
        enabled     = $true
    }
}

$mods | ConvertTo-Json -Depth 5 | Set-Content $modsJsonPath -NoNewline

# --- rebuild compiled zen-themes.css (what Zen injects at startup) --------------
# Mirrors ZenMods.mjs #writeStylesheet: concatenate every enabled mod's chrome.css.
$content = "/* Zen Mods - Generated by ZenMods.`n"
$content += "* FILE GENERATED AT: $(Get-Date)`n"
$content += "* DO NOT EDIT THIS FILE DIRECTLY!`n* Your changes will be overwritten.`n"
$content += "* Instead, go to the preferences and edit the mods there.`n*/`n"

foreach ($mod in $mods.Values) {
    if ($mod.enabled -eq $false) { continue }
    $cssPath = Join-Path $modsRoot (Join-Path $mod.id "chrome.css")
    if (-not (Test-Path $cssPath)) { continue }
    $content += "`n/* Name: $($mod.name) */`n"
    $content += "/* Description: $($mod.description) */`n"
    $content += "/* Author: @$($mod.author) */`n"
    $content += Get-Content $cssPath -Raw
}
$content += "`n/* End of Zen Mods */"

New-Item -ItemType Directory -Force (Split-Path $compiledCss) | Out-Null
Set-Content $compiledCss $content -NoNewline

if ($Uninstall) {
    Write-Host "Lucid Tabs removed. Restart Zen to apply."
} else {
    Write-Host "Lucid Tabs $($theme.version) installed. Restart Zen to apply."
}
